# Generated by Django 5.2.13 on 2026-07-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=50)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='careers/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('course', 'Course Completion'), ('internship', 'Internship'), ('workshop', 'Workshop'), ('project', 'Live Project')], default='course', max_length=20, verbose_name='Certificate Type')),
                ('course_name', models.CharField(help_text="e.g. 'Python Full Stack Development'", max_length=200)),
                ('image', models.ImageField(help_text='Upload certificate image/scan', upload_to='certificates/')),
                ('description', models.TextField(blank=True, help_text='Optional tagline shown under the certificate')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('project_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=200)),
                ('year_passed', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('demo_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('syllabus', models.JSONField(help_text='Enter syllabus items as a list')),
                ('image', models.ImageField(blank=True, null=True, upload_to='internships/')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_image', models.ImageField(upload_to='placements/')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('job_role', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('placed_year', models.PositiveIntegerField()),
                ('course', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-search', help_text='Bootstrap Icon class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('technologies', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Django, Bootstrap, PostgreSQL, REST API'", max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_offers/')),
                ('link_url', models.CharField(help_text='e.g., /internships/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('course_name', models.CharField(max_length=150)),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Prefer not to say')], default='M', help_text='Used for default anime avatar if no custom image is uploaded', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('registration_info', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='upcoming_workshops/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Python Bootcamp – March 2025'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short caption shown under the photo (optional)')),
                ('image', models.ImageField(help_text='Upload workshop photo', upload_to='workshop_photos/')),
                ('event_date', models.DateField(blank=True, help_text='Date the workshop was held (optional)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workshop Photo',
                'verbose_name_plural': 'Workshop Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('participation_mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=50, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('passed_out_year', models.CharField(blank=True, max_length=10, null=True)),
                ('interested_domains', models.TextField(blank=True, help_text='Comma separated selected domains', null=True)),
                ('technical_skill', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Basic Knowledge', 'Basic Knowledge'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Other', 'Other')], max_length=30, null=True)),
                ('technical_skill_other', models.CharField(blank=True, max_length=200, null=True)),
                ('demo_interest', models.CharField(blank=True, choices=[('Yes', 'Yes, I want to Attend a Free Demo Session on my Interested Domain'), ('Maybe', 'Maybe'), ('Need more information', 'Need more information'), ('No', 'No'), ('Other', 'Other')], max_length=40, null=True)),
                ('demo_interest_other', models.CharField(blank=True, max_length=200, null=True)),
                ('demo_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Either', 'Either is Okay')], max_length=20, null=True)),
                ('preferred_demo_time', models.CharField(blank=True, help_text='Comma separated selected time slots', max_length=200, null=True)),
                ('consent', models.BooleanField(blank=True, default=False, null=True)),
                ('queries', models.TextField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('custom_requirement', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.democategory')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=200)),
                ('year_passed_out', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField()),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.career')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDemoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'E-commerce Demo', 'Portfolio Demo'", max_length=150)),
                ('image', models.FileField(blank=True, null=True, upload_to='service_images/')),
                ('url', models.URLField(blank=True, help_text='Full link to the live demo site', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('description', models.CharField(blank=True, help_text='Short one-line description shown on the Live Demo card', max_length=300)),
                ('category', models.CharField(blank=True, help_text="e.g. 'Education', 'CRM', 'Hotel', 'Portfolio' — used for Live Demo filters", max_length=100)),
                ('technologies', models.CharField(blank=True, help_text="Comma-separated, e.g. 'HTML, CSS, JS'", max_length=300)),
                ('is_featured', models.BooleanField(default=True, help_text="Show this on its Service's detail page (uncheck to keep it Live-Demo-page-only)")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_links', to='main.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.service')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-check-circle', help_text="Bootstrap Icon class, e.g. 'bi-rocket-takeoff' — browse icons.getbootstrap.com", max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
